In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
%matplotlib inline
digits = load_digits()

In [3]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [5]:
# Logistic Regression
lr = LogisticRegression(solver='liblinear', multi_class='ovr')
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

0.9648148148148148

In [7]:
# SVM 
svm = SVC(gamma='auto')
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.3685185185185185

In [9]:
# Random Forest
rf = RandomForestClassifier(n_estimators=40)
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.987037037037037

<b>K-Fold Cross Validation</b>

In [12]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [14]:
def get_score(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [16]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

score_lr = []
score_svm = []
score_rf = []

for train_index, test_index in folds.split(digits.data, digits.target):
    x_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index], digits.target[train_index], digits.target[test_index]

    score_lr.append(get_score(LogisticRegression(solver='liblinear', multi_class='ovr'), x_train, x_test, y_train, y_test))  
    score_svm.append(get_score(SVC(gamma='auto'), x_train, x_test, y_train, y_test))
    score_rf.append(get_score(RandomForestClassifier(n_estimators=40), x_train, x_test, y_train, y_test))

In [17]:
score_lr

[0.8948247078464107, 0.9532554257095158, 0.9098497495826378]

In [20]:
score_svm

[0.3806343906510851, 0.41068447412353926, 0.5125208681135225]

In [22]:
score_rf

[0.9298831385642737, 0.9482470784641068, 0.9198664440734557]

<b>Cross_val_score Function</b>

In [25]:
from sklearn.model_selection import cross_val_score

In [27]:
# Logistic Regression
cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), digits.data, digits.target,cv=3)

array([0.89482471, 0.95325543, 0.90984975])

In [29]:
# SVM 
cross_val_score(SVC(gamma='auto'), digits.data, digits.target, cv=3)

array([0.38063439, 0.41068447, 0.51252087])

In [30]:
# Random Forest
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target, cv=3)

array([0.93322204, 0.95158598, 0.90984975])

<b>Parameter Tuning with K-Fold cross validation</b>

In [34]:
score1 = cross_val_score(RandomForestClassifier(n_estimators=5), digits.data, digits.target, cv=3)
np.average(score1)

0.8430717863105176

In [36]:
score2 = cross_val_score(RandomForestClassifier(n_estimators=20), digits.data, digits.target, cv=3)
np.average(score2)

0.9187534780189205

In [38]:
score3 = cross_val_score(RandomForestClassifier(n_estimators=30), digits.data, digits.target, cv=3)
np.average(score3)

0.9309961046188091

In [40]:
score4 = cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target, cv=3)
np.average(score4)

0.9360044518642181

Here we used cross_val_score to fine tune our random forest classifier and figured that having around 40 trees in random forest gives best result.