In [3]:
from sklearn.datasets import load_iris
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
iris = load_iris()

<b>Logistic Regression</b>

In [55]:
lr_scores = cross_val_score(LogisticRegression(), iris.data, iris.target, cv=3)
lr_scores

C:\Users\91798\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.98, 0.96, 0.98])

In [57]:
np.average(lr_scores)

0.9733333333333333

<b>Decision Tree</b>

In [59]:
dt_scores = cross_val_score(DecisionTreeClassifier(), iris.data, iris.target, cv=3)
dt_scores

array([0.98, 0.94, 0.96])

In [61]:
np.average(dt_scores)

0.96

<b>Support Vector Machine (SVM)</b>

In [63]:
s_scores = cross_val_score(SVC(), iris.data, iris.target, cv=3)
s_scores

array([0.96, 0.98, 0.94])

In [65]:
np.average(s_scores)

0.96

<b>Random Forest</b>

In [67]:
r_scores = cross_val_score(RandomForestClassifier(n_estimators=40), iris.data, iris.target, cv=3)
r_scores

array([0.98, 0.94, 0.98])

In [69]:
np.average(r_scores)

0.9666666666666667